### PR TITLE
Update html-webpack-plugin v5

### PR DESCRIPTION
**Pull request by strootje**
This PR fixes some typing errors for webpack and updated the html-webpack-plugin to v5 (alpha).
Also fixes a deprecation error with webpack. (see #144)

### CODE REVIEW

**Comment by strootje** [comment]
Apparently a dependency from the terser-webpack-plugin dropped node 8/9 support:
https://github.com/sindresorhus/p-limit/commit/b35faf54fb0871d9ae592069a18083a2ba15d8a9

**Comment by elyobo** [comment]
`html-webpack-plugin`  now has a 5.x series out of alpha FYI

**Comment by TheRealFlyingCoder** [comment]
Is there anything stopping this from merging?

I'm also waiting on the Typing updates eagerly 😄

**Comment by TikiTDO** [comment]
@arthurbergmz Is there any chance to merge this PR? If you're not comfortable pulling an alpha version of `html-webpack-plugin` and if @strootje is no longer available I'd be happy to update the PR to use `html-webpack-plugin` 5.3.1

**Comment by strootje** [comment]
I've updated the `html-webpack-plugin` and the `webpack` package to their latest versions.

**Comment by strootje** [comment]
@arthurbergmz any chance to review / complete this?

**Comment by julioxavierr** [comment]
+1

**Comment by icetee** [comment]
I try install your branch, but I get error.

```
npm uninstall webpack-pwa-manifest && npm install strootje/webpack-pwa-manifest#update-webpack-v5 --save-dev
```

```
[webpack-cli] Failed to load '/app/webpack.config.js' config
[webpack-cli] Error: Cannot find module './dist/index.js'
Require stack:
- /app/node_modules/webpack-pwa-manifest/index.js
- /app/webpack.config.js
- /app/node_modules/webpack-cli/lib/webpack-cli.js
- /app/node_modules/webpack-cli/lib/bootstrap.js
- /app/node_modules/webpack-cli/bin/cli.js
- /app/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/app/node_modules/webpack-pwa-manifest/index.js:1:80)
    at Module._compile (/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/webpack-pwa-manifest/index.js',
    '/app/webpack.config.js',
    '/app/node_modules/webpack-cli/lib/webpack-cli.js',
    '/app/node_modules/webpack-cli/lib/bootstrap.js',
    '/app/node_modules/webpack-cli/bin/cli.js',
    '/app/node_modules/webpack/bin/webpack.js'
  ]
}
```

**Comment by strootje** [comment]
> I try install your branch, but I get error.

I just tried installing my branch as well and for me it is working. Can you maybe provide more info as to what you are trying.

For anybody trying to get this package to work install it like this: `npm install strootje/webpack-pwa-manifest#update-webpack-v5`. This will grab the version from github and build it on the spot.

@arthurbergmz a review would be nice.

**Comment by TbIKoBKa** [comment]
> I try install your branch, but I get error.
> 
> ```
> npm uninstall webpack-pwa-manifest && npm install strootje/webpack-pwa-manifest#update-webpack-v5 --save-dev
> ```
> 
> ```
> [webpack-cli] Failed to load '/app/webpack.config.js' config
> [webpack-cli] Error: Cannot find module './dist/index.js'
> Require stack:
> - /app/node_modules/webpack-pwa-manifest/index.js
> - /app/webpack.config.js
> - /app/node_modules/webpack-cli/lib/webpack-cli.js
> - /app/node_modules/webpack-cli/lib/bootstrap.js
> - /app/node_modules/webpack-cli/bin/cli.js
> - /app/node_modules/webpack/bin/webpack.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
>     at Object.<anonymous> (/app/node_modules/webpack-pwa-manifest/index.js:1:80)
>     at Module._compile (/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/app/node_modules/webpack-pwa-manifest/index.js',
>     '/app/webpack.config.js',
>     '/app/node_modules/webpack-cli/lib/webpack-cli.js',
>     '/app/node_modules/webpack-cli/lib/bootstrap.js',
>     '/app/node_modules/webpack-cli/bin/cli.js',
>     '/app/node_modules/webpack/bin/webpack.js'
>   ]
> }
> ```
@icetee
Same issue. Did you solve it?

**Pull request closed without merging**
