### PR TITLE
fix: catch failing require of html-webpack-plugin

### PR DESCRIPTION
**Pull request by JeandeCampredon**
This is quick fixing, I haven't much time for looking further though I couldn't let it slips. 
So hope it helps.
Enjoy

### CODE REVIEW

**Comment by greggb** [comment]
This does fix the error in #111

**Comment by greggb** [comment]
@arthurbergmz If you get a chance to merge and cut a release this change would allow us to safely update to the latest version. Many thanks!

**Comment by thasmo** [comment]
@arthurbergmz, any chance this will make it into a patch release soon? At the moment the latest version is pretty much unusable on projects which do not use `html-webpack-plugin`. Thanks!

**Comment by thasmo** [comment]
@arthurbergmz, you gonna look at this? Thanks!

**Comment by max-scopp** [comment]
LGTM, people need it @arthurbergmz

**Pull request merged**
