### PR TITLE
chore: add support for html-webpack-plugin v4

### PR DESCRIPTION
**Pull request by JeandeCampredon**
I am using html-webpack-plugin v4

and After reading this issue: 
https://github.com/arthurbergmz/webpack-pwa-manifest/issues/56

I tried to solve my injection problem, also following html-webpack-plugin README.md examples helped me through

Hope it might help

### CODE REVIEW

**Comment by silentsakky** [comment]
Can we please merge this? we need this in our environment

**Comment by JeandeCampredon** [comment]
@silentsakky feel free to use my repo temp branch https://github.com/JeandeCampredon/webpack-pwa-manifest/tree/temp directly in you module

**Comment by cruzdanilo** [comment]
please, merge this.

**Comment by sirjuan** [comment]
Please merge, otherwise this plugin is unusable with Create React App that uses html-webpack-plugin 4.0.0beta.

**Comment by laznic** [comment]
@arthurbergmz could we get this merged please?

**Comment by makker** [comment]
Would be awesome to get this merged. Thanks advance!

**Comment by ruimarinho** [comment]
@arthurbergmz can you publish to nom? :) thanks a lot!

**Comment by sirjuan** [comment]
@arthurbergmz thank you for merging this! However latest npm publish has [an issue](https://github.com/arthurbergmz/webpack-pwa-manifest/issues/110) with missing dist-directory.

**Pull request merged**
