### PR TITLE
fix(icons): use uppercase at import according to filename

### PR DESCRIPTION
**Pull request by escapedcat**

### CODE REVIEW

**Comment by escapedcat** [comment]
For some reason our CI failed after the last update and said:
`Error: Cannot find module '../icons'`  

The filename is `Icons.js`. It worked locally because OSX doesn't care, but our CI did not like it.  
To be honest I am not sure why it didn't fail before, but this fixes it.

(Ok, closed this PR before because I didn't test it. Now I did and it looks fine.)

**Comment by escapedcat** [comment]
For some reason our CI failed after the last update and said:
`Error: Cannot find module '../icons'`  

The filename is `Icons.js`. It worked locally because OSX doesn't care, but our CI did not like it.  
To be honest I am not sure why it didn't fail before, but this fixes it.

(Ok, closed this PR before because I didn't test it. Now I did and it looks fine.)

**Comment by arthurbergmz** [comment]
Oops, my bad, I'm going to lowercase the filename just because of convention.
Thank you!

**Comment by arthurbergmz** [comment]
Please, update to **v3.4.1**.

**Comment by escapedcat** [comment]
Even better, thx! 👏

**Pull request closed without merging**
